# Generated by Django 4.1.3 on 2022-11-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0002_alter_register_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
